version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails server -b 0.0.0.0
    ports:
      - 3000:3000
      - 1234:1234
      - 26162:26162
    volumes:
      - .:/app
    env_file:
      - ./rails.env
    environment:
      RAILS_ENV: development
    networks:
      - local_network
networks:
  local_network:
    driver: 'bridge'