version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec bin/rails server -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - local_network
networks:
  local_network:
    driver: 'bridge'